In [1]:
import pandas as pd

In [2]:
d=pd.read_csv('/kaggle/input/datasets/hemanthkumar28/workspace-rental-price-tier-prediction-dataset/kaggle_ready_dataset/train.csv')

In [3]:
d.head()

,space_id,operator_ref,operator_platform_age_years,operator_platform_age_months,operator_active_years,operator_active_months,operator_class,operator_certified,operator_portfolio_size,operator_has_avatar,...,score_access,score_value,compliance_status,operator_metro_units,operator_metro_whole,operator_metro_private,operator_metro_shared,reviews_per_month,metro,price_tier
0,0,Bralchu,12.0,8.0,7.0,8.0,independent_operator,f,2.0,t,...,9.12,9.54,unlicensed,2,0,2,0,0.42,MTR-09,2
1,1,Grorfian,2.0,2.0,2.0,2.0,independent_operator,f,3.0,t,...,NaN,NaN,unlicensed,3,1,2,0,NaN,MTR-01,1
2,2,Snelenr,10.0,10.0,7.0,10.0,independent_operator,f,1.0,t,...,10.00,10.00,unlicensed,1,1,0,0,0.03,MTR-01,2
3,3,Spesspe,2.0,1.0,2.0,1.0,unverified_operator,t,1.0,t,...,10.00,10.00,unlicensed,1,1,0,0,0.60,MTR-09,4
4,4,Gosho,2.0,7.0,2.0,4.0,unverified_operator,t,1.0,t,...,9.42,9.74,licensed,1,1,0,0,4.64,MTR-08,3

In [4]:
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [5]:
d.head()

,space_id,operator_ref,operator_platform_age_years,operator_platform_age_months,operator_active_years,operator_active_months,operator_class,operator_certified,operator_portfolio_size,operator_has_avatar,operator_id_verified,zone,borough,geo_lat,geo_lon,space_class,access_type,max_seats,utility_rooms,zones,workstations,facilities,snapshot_start_date,snapshot_end_date,min_term_days,max_term_days,min_term_floor,min_term_ceiling,max_term_floor,max_term_ceiling,min_term_avg,max_term_avg,bookable,open_slots_a,open_slots_b,open_slots_c,open_slots_d,review_count,review_count_12m,review_count_30d,open_slots_e,review_count_prev_yr,booked_load,first_review_date,last_review_date,score_overall,score_accuracy,score_condition,score_onboarding,score_support,score_access,score_value,compliance_status,operator_metro_units,operator_metro_whole,operator_metro_private,operator_metro_shared,reviews_per_month,metro,price_tier
0,0,Bralchu,12.0,8.0,7.0,8.0,independent_operator,f,2.0,t,t,ZN-0557,NaN,111.7005,-31.1170,Boutique Workroom,private_zone,2,1.0,NaN,1.0,"[""FCL-087"", ""FCL-007"", ""FCL-085"", ""FCL-072"", ""...",2024-08-20,2024-08-22,2.0,31.0,2.0,2.0,31.0,31.0,2.0,31.0,t,23,53,83,173,39,2,0,173,2,18,2016-11-03,2023-08-18,9.44,9.74,9.54,9.70,9.74,9.12,9.54,unlicensed,2,0,2,0,0.42,MTR-09,2
1,1,Grorfian,2.0,2.0,2.0,2.0,independent_operator,f,3.0,t,t,ZN-0082,BRG-18,88.0215,-123.2818,Boutique Workroom,private_zone,1,2.0,1.0,1.0,"[""FCL-135"", ""FCL-136"", ""FCL-141"", ""FCL-077"", ""...",2024-08-24,2024-09-24,30.0,120.0,30.0,30.0,120.0,120.0,30.0,120.0,t,15,45,75,75,0,0,0,75,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unlicensed,3,1,2,0,NaN,MTR-01,1
2,2,Snelenr,10.0,10.0,7.0,10.0,independent_operator,f,1.0,t,t,ZN-0082,BRG-18,88.0350,-123.2662,Ground Bay,whole_unit,2,1.0,1.0,1.0,"[""FCL-019"", ""FCL-136"", ""FCL-135"", ""FCL-043"", ""...",2024-08-09,2024-09-09,30.0,1125.0,30.0,30.0,1125.0,1125.0,30.0,1125.0,t,30,60,90,270,2,0,0,199,0,0,2019-09-02,2021-07-25,10.00,10.00,10.00,10.00,10.00,10.00,10.00,unlicensed,1,1,0,0,0.03,MTR-01,2
3,3,Spesspe,2.0,1.0,2.0,1.0,unverified_operator,t,1.0,t,t,ZN-0654,NaN,111.5520,-31.1638,Flex Bay,whole_unit,2,1.0,1.0,1.0,"[""FCL-073"", ""FCL-145"", ""FCL-019"", ""FCL-040"", ""...",2024-08-22,2024-08-23,1.0,1125.0,1.0,1.0,1125.0,1125.0,1.0,1125.0,t,8,30,30,189,1,1,0,111,0,9,2024-06-01,2024-06-01,10.00,10.00,10.00,10.00,10.00,10.00,10.00,unlicensed,1,1,0,0,0.60,MTR-09,4
4,4,Gosho,2.0,7.0,2.0,4.0,unverified_operator,t,1.0,t,t,ZN-0387,BRG-45,96.8640,-88.6420,Enclosed Alcove,whole_unit,2,1.0,1.0,1.0,"[""FCL-058"", ""FCL-093"", ""FCL-142"", ""FCL-040"", ""...",2024-08-13,2024-08-15,1.0,20.0,1.0,2.0,20.0,20.0,2.0,20.0,t,17,43,72,72,119,49,5,72,58,255,2022-06-01,2024-07-04,9.88,9.94,9.92,9.88,9.94,9.42,9.74,licensed,1,1,0,0,4.64,MTR-08,3

In [6]:
d=d.drop(columns='facilities')

In [7]:
d.head()

,space_id,operator_ref,operator_platform_age_years,operator_platform_age_months,operator_active_years,operator_active_months,operator_class,operator_certified,operator_portfolio_size,operator_has_avatar,operator_id_verified,zone,borough,geo_lat,geo_lon,space_class,access_type,max_seats,utility_rooms,zones,workstations,snapshot_start_date,snapshot_end_date,min_term_days,max_term_days,min_term_floor,min_term_ceiling,max_term_floor,max_term_ceiling,min_term_avg,max_term_avg,bookable,open_slots_a,open_slots_b,open_slots_c,open_slots_d,review_count,review_count_12m,review_count_30d,open_slots_e,review_count_prev_yr,booked_load,first_review_date,last_review_date,score_overall,score_accuracy,score_condition,score_onboarding,score_support,score_access,score_value,compliance_status,operator_metro_units,operator_metro_whole,operator_metro_private,operator_metro_shared,reviews_per_month,metro,price_tier
0,0,Bralchu,12.0,8.0,7.0,8.0,independent_operator,f,2.0,t,t,ZN-0557,NaN,111.7005,-31.1170,Boutique Workroom,private_zone,2,1.0,NaN,1.0,2024-08-20,2024-08-22,2.0,31.0,2.0,2.0,31.0,31.0,2.0,31.0,t,23,53,83,173,39,2,0,173,2,18,2016-11-03,2023-08-18,9.44,9.74,9.54,9.70,9.74,9.12,9.54,unlicensed,2,0,2,0,0.42,MTR-09,2
1,1,Grorfian,2.0,2.0,2.0,2.0,independent_operator,f,3.0,t,t,ZN-0082,BRG-18,88.0215,-123.2818,Boutique Workroom,private_zone,1,2.0,1.0,1.0,2024-08-24,2024-09-24,30.0,120.0,30.0,30.0,120.0,120.0,30.0,120.0,t,15,45,75,75,0,0,0,75,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unlicensed,3,1,2,0,NaN,MTR-01,1
2,2,Snelenr,10.0,10.0,7.0,10.0,independent_operator,f,1.0,t,t,ZN-0082,BRG-18,88.0350,-123.2662,Ground Bay,whole_unit,2,1.0,1.0,1.0,2024-08-09,2024-09-09,30.0,1125.0,30.0,30.0,1125.0,1125.0,30.0,1125.0,t,30,60,90,270,2,0,0,199,0,0,2019-09-02,2021-07-25,10.00,10.00,10.00,10.00,10.00,10.00,10.00,unlicensed,1,1,0,0,0.03,MTR-01,2
3,3,Spesspe,2.0,1.0,2.0,1.0,unverified_operator,t,1.0,t,t,ZN-0654,NaN,111.5520,-31.1638,Flex Bay,whole_unit,2,1.0,1.0,1.0,2024-08-22,2024-08-23,1.0,1125.0,1.0,1.0,1125.0,1125.0,1.0,1125.0,t,8,30,30,189,1,1,0,111,0,9,2024-06-01,2024-06-01,10.00,10.00,10.00,10.00,10.00,10.00,10.00,unlicensed,1,1,0,0,0.60,MTR-09,4
4,4,Gosho,2.0,7.0,2.0,4.0,unverified_operator,t,1.0,t,t,ZN-0387,BRG-45,96.8640,-88.6420,Enclosed Alcove,whole_unit,2,1.0,1.0,1.0,2024-08-13,2024-08-15,1.0,20.0,1.0,2.0,20.0,20.0,2.0,20.0,t,17,43,72,72,119,49,5,72,58,255,2022-06-01,2024-07-04,9.88,9.94,9.92,9.88,9.94,9.42,9.74,licensed,1,1,0,0,4.64,MTR-08,3

In [8]:
d.isnull().sum()

space_id                             0
operator_ref                       604
operator_platform_age_years        604
operator_platform_age_months       604
operator_active_years              606
operator_active_months             606
operator_class                       0
operator_certified                 604
operator_portfolio_size            604
operator_has_avatar                604
operator_id_verified               604
zone                                 0
borough                         214451
geo_lat                              0
geo_lon                              0
space_class                          0
access_type                          0
max_seats                            0
utility_rooms                    29899
zones                            48414
workstations                     18783
snapshot_start_date                  0
snapshot_end_date                    0
min_term_days                       41
max_term_days                       41
min_term_floor                      41
min_term_ceiling                    41
max_term_floor                      41
max_term_ceiling                    41
min_term_avg                         0
max_term_avg                         0
bookable                            97
open_slots_a                         0
open_slots_b                         0
open_slots_c                         0
open_slots_d                         0
review_count                         0
review_count_12m                     0
review_count_30d                     0
open_slots_e                         0
review_count_prev_yr                 0
booked_load                          0
first_review_date                54240
last_review_date                 54240
score_overall                    54236
score_accuracy                   54242
score_condition                  54240
score_onboarding                 54243
score_support                    54241
score_access                     54245
score_value                      54246
compliance_status                    0
operator_metro_units                 0
operator_metro_whole                 0
operator_metro_private               0
operator_metro_shared                0
reviews_per_month                54240
metro                                0
price_tier                           0
dtype: int64

In [9]:
d.head()

,space_id,operator_ref,operator_platform_age_years,operator_platform_age_months,operator_active_years,operator_active_months,operator_class,operator_certified,operator_portfolio_size,operator_has_avatar,operator_id_verified,zone,borough,geo_lat,geo_lon,space_class,access_type,max_seats,utility_rooms,zones,workstations,snapshot_start_date,snapshot_end_date,min_term_days,max_term_days,min_term_floor,min_term_ceiling,max_term_floor,max_term_ceiling,min_term_avg,max_term_avg,bookable,open_slots_a,open_slots_b,open_slots_c,open_slots_d,review_count,review_count_12m,review_count_30d,open_slots_e,review_count_prev_yr,booked_load,first_review_date,last_review_date,score_overall,score_accuracy,score_condition,score_onboarding,score_support,score_access,score_value,compliance_status,operator_metro_units,operator_metro_whole,operator_metro_private,operator_metro_shared,reviews_per_month,metro,price_tier
0,0,Bralchu,12.0,8.0,7.0,8.0,independent_operator,f,2.0,t,t,ZN-0557,NaN,111.7005,-31.1170,Boutique Workroom,private_zone,2,1.0,NaN,1.0,2024-08-20,2024-08-22,2.0,31.0,2.0,2.0,31.0,31.0,2.0,31.0,t,23,53,83,173,39,2,0,173,2,18,2016-11-03,2023-08-18,9.44,9.74,9.54,9.70,9.74,9.12,9.54,unlicensed,2,0,2,0,0.42,MTR-09,2
1,1,Grorfian,2.0,2.0,2.0,2.0,independent_operator,f,3.0,t,t,ZN-0082,BRG-18,88.0215,-123.2818,Boutique Workroom,private_zone,1,2.0,1.0,1.0,2024-08-24,2024-09-24,30.0,120.0,30.0,30.0,120.0,120.0,30.0,120.0,t,15,45,75,75,0,0,0,75,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unlicensed,3,1,2,0,NaN,MTR-01,1
2,2,Snelenr,10.0,10.0,7.0,10.0,independent_operator,f,1.0,t,t,ZN-0082,BRG-18,88.0350,-123.2662,Ground Bay,whole_unit,2,1.0,1.0,1.0,2024-08-09,2024-09-09,30.0,1125.0,30.0,30.0,1125.0,1125.0,30.0,1125.0,t,30,60,90,270,2,0,0,199,0,0,2019-09-02,2021-07-25,10.00,10.00,10.00,10.00,10.00,10.00,10.00,unlicensed,1,1,0,0,0.03,MTR-01,2
3,3,Spesspe,2.0,1.0,2.0,1.0,unverified_operator,t,1.0,t,t,ZN-0654,NaN,111.5520,-31.1638,Flex Bay,whole_unit,2,1.0,1.0,1.0,2024-08-22,2024-08-23,1.0,1125.0,1.0,1.0,1125.0,1125.0,1.0,1125.0,t,8,30,30,189,1,1,0,111,0,9,2024-06-01,2024-06-01,10.00,10.00,10.00,10.00,10.00,10.00,10.00,unlicensed,1,1,0,0,0.60,MTR-09,4
4,4,Gosho,2.0,7.0,2.0,4.0,unverified_operator,t,1.0,t,t,ZN-0387,BRG-45,96.8640,-88.6420,Enclosed Alcove,whole_unit,2,1.0,1.0,1.0,2024-08-13,2024-08-15,1.0,20.0,1.0,2.0,20.0,20.0,2.0,20.0,t,17,43,72,72,119,49,5,72,58,255,2022-06-01,2024-07-04,9.88,9.94,9.92,9.88,9.94,9.42,9.74,licensed,1,1,0,0,4.64,MTR-08,3

In [10]:
d=d.drop(columns=['space_id','zone','borough','geo_lat','geo_lon','space_class','access_type','snapshot_start_date','snapshot_end_date','first_review_date','last_review_date','metro'])

In [11]:
d.shape

(279746, 47)

In [12]:
d.head()

,operator_ref,operator_platform_age_years,operator_platform_age_months,operator_active_years,operator_active_months,operator_class,operator_certified,operator_portfolio_size,operator_has_avatar,operator_id_verified,max_seats,utility_rooms,zones,workstations,min_term_days,max_term_days,min_term_floor,min_term_ceiling,max_term_floor,max_term_ceiling,min_term_avg,max_term_avg,bookable,open_slots_a,open_slots_b,open_slots_c,open_slots_d,review_count,review_count_12m,review_count_30d,open_slots_e,review_count_prev_yr,booked_load,score_overall,score_accuracy,score_condition,score_onboarding,score_support,score_access,score_value,compliance_status,operator_metro_units,operator_metro_whole,operator_metro_private,operator_metro_shared,reviews_per_month,price_tier
0,Bralchu,12.0,8.0,7.0,8.0,independent_operator,f,2.0,t,t,2,1.0,NaN,1.0,2.0,31.0,2.0,2.0,31.0,31.0,2.0,31.0,t,23,53,83,173,39,2,0,173,2,18,9.44,9.74,9.54,9.70,9.74,9.12,9.54,unlicensed,2,0,2,0,0.42,2
1,Grorfian,2.0,2.0,2.0,2.0,independent_operator,f,3.0,t,t,1,2.0,1.0,1.0,30.0,120.0,30.0,30.0,120.0,120.0,30.0,120.0,t,15,45,75,75,0,0,0,75,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unlicensed,3,1,2,0,NaN,1
2,Snelenr,10.0,10.0,7.0,10.0,independent_operator,f,1.0,t,t,2,1.0,1.0,1.0,30.0,1125.0,30.0,30.0,1125.0,1125.0,30.0,1125.0,t,30,60,90,270,2,0,0,199,0,0,10.00,10.00,10.00,10.00,10.00,10.00,10.00,unlicensed,1,1,0,0,0.03,2
3,Spesspe,2.0,1.0,2.0,1.0,unverified_operator,t,1.0,t,t,2,1.0,1.0,1.0,1.0,1125.0,1.0,1.0,1125.0,1125.0,1.0,1125.0,t,8,30,30,189,1,1,0,111,0,9,10.00,10.00,10.00,10.00,10.00,10.00,10.00,unlicensed,1,1,0,0,0.60,4
4,Gosho,2.0,7.0,2.0,4.0,unverified_operator,t,1.0,t,t,2,1.0,1.0,1.0,1.0,20.0,1.0,2.0,20.0,20.0,2.0,20.0,t,17,43,72,72,119,49,5,72,58,255,9.88,9.94,9.92,9.88,9.94,9.42,9.74,licensed,1,1,0,0,4.64,3

In [13]:
d=d.drop(columns='operator_ref')

In [14]:
d['operator_class'].value_counts()

operator_class
unverified_operator     127473
independent_operator    111887
managed_operator         40386
Name: count, dtype: int64

In [15]:
d['operator_certified'].value_counts()

operator_certified
f    180235
t     98907
Name: count, dtype: int64

In [16]:
d=d.drop(columns=['operator_has_avatar','operator_id_verified'])

In [17]:
d['zones'].value_counts()

zones
1.0     135615
2.0      60140
3.0      23438
4.0       7897
5.0       2534
6.0        894
7.0        287
8.0        177
9.0         77
10.0        75
0.0         40
12.0        32
14.0        18
11.0        18
16.0        15
15.0        13
20.0         9
13.0         9
25.0         6
18.0         5
22.0         4
50.0         4
46.0         3
28.0         3
31.0         3
27.0         2
24.0         2
30.0         2
23.0         1
19.0         1
21.0         1
26.0         1
29.0         1
36.0         1
40.0         1
32.0         1
39.0         1
35.0         1
Name: count, dtype: int64